version: '3.8'

# 服務定義 Services definition
services:
  # 數據庫服務 Database service
  postgres:
    container_name: talent-postgres-prod
    image: postgres:16-alpine
    expose:
      - "5432"  # 只暴露端口，不直接對外開放
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=${DB_NAME:-class_schedule}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - TZ=Asia/Taipei
      - PGTZ=Asia/Taipei
    command: postgres -c timezone=Asia/Taipei
    networks:
      - talent-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 後端服務 Backend service
  backend:
    container_name: talent-backend-prod
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: talent-backend-prod
    expose:
      - "9006"  # 只暴露端口，不直接對外開放
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-class_schedule}
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://18.140.56.99:8080
      - TZ=Asia/Taipei
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - talent-network
    restart: always

  # 前端服務 Frontend service
  frontend:
    container_name: talent-frontend-prod
    build:
      context: ../../web
      dockerfile: Dockerfile
    image: talent-frontend-prod
    expose:
      - "9080"  # 只暴露端口，不直接對外開放
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=/schedule-api
      - TZ=Asia/Taipei
    networks:
      - talent-network
    restart: always

  # Nginx 反向代理服務 Nginx reverse proxy service
  nginx:
    container_name: talent-nginx-prod
    image: nginx:alpine
    ports:
      - "80:80"  # 使用 80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - talent-network
    restart: always

# 卷定義 Volumes definition
volumes:
  postgres_data:

# 網絡定義 Networks definition
networks:
  talent-network:
    driver: bridge 