version: '3.8'

# 服務定義 Services definition
services:
  # 前端服務 Frontend service
  frontend:
    container_name: talent-frontend-prod
    build:
      context: ../../web
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - TZ=Asia/Taipei
    depends_on:
      - backend
    networks:
      - talent-network-prod
    restart: always

  # 後端服務 Backend service
  backend:
    container_name: talent-backend-prod
    build:
      context: ../../server
      dockerfile: Dockerfile.prod
    ports:
      - "24128:3006"
    environment:
      - NODE_ENV=production
      - PORT=3006
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=class_schedule
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=24h
      - TZ=Asia/Taipei
    depends_on:
      - database
    networks:
      - talent-network-prod
    restart: always

  # 數據庫服務 Database service
  database:
    container_name: talent-postgres-prod
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - /data/class-schedule/postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=class_schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Taipei
      - PGTZ=Asia/Taipei
    command: postgres -c timezone=Asia/Taipei
    networks:
      - talent-network-prod
    restart: always

# 卷定義 Volumes definition
volumes:
  talent-postgres-data-prod:
    name: talent-postgres-data-prod

# 網絡定義 Networks definition
networks:
  talent-network-prod:
    name: talent-network-prod 