version: '3.8'

# 服務定義 Services definition
services:
  # Nginx 反向代理服務 Nginx reverse proxy service
  nginx:
    container_name: talent-nginx-prod
    image: nginx:alpine
    ports:
      - "8080:80"  # 使用 8080 端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - talent-network
    restart: always

  # 前端服務 Frontend service
  frontend:
    container_name: talent-frontend-prod
    build:
      context: ../../web
      dockerfile: Dockerfile
    image: talent-frontend-prod
    expose:
      - "80"  # 只暴露端口，不直接對外開放
    environment:
      - NODE_ENV=production
      - TZ=Asia/Taipei
    networks:
      - talent-network
    restart: always

  # 後端服務 Backend service
  backend:
    container_name: talent-backend-prod
    build:
      context: ../../server
      dockerfile: Dockerfile
    image: talent-backend-prod
    expose:
      - "3006"  # 只暴露端口，不直接對外開放
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=talent_db
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - CORS_ORIGIN=http://18.140.56.99:8080
      - TZ=Asia/Taipei
    depends_on:
      - postgres
    networks:
      - talent-network
    restart: always

  # 數據庫服務 Database service
  postgres:
    container_name: talent-postgres-prod
    image: postgres:15
    expose:
      - "5432"  # 只暴露端口，不直接對外開放
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=talent_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Taipei
      - PGTZ=Asia/Taipei
    command: postgres -c timezone=Asia/Taipei
    networks:
      - talent-network
    restart: always

# 卷定義 Volumes definition
volumes:
  postgres_data:

# 網絡定義 Networks definition
networks:
  talent-network:
    driver: bridge 