version: '3.8'

# 服務定義 Services definition
services:
  # 前端服務 Frontend service
  frontend:
    container_name: talent-frontend-dev
    build:
      context: ../../web
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ../../web:/app
      - /app/node_modules
      # 掛載主機時間文件 Mount host timezone file
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=development
      - TZ=Asia/Taipei
    depends_on:
      - backend
    networks:
      - talent-network
    # 啟用熱重載 Enable hot reload
    command: npm run dev

  # 後端服務 Backend service
  backend:
    container_name: talent-backend-dev
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - ../../server:/app
      - /app/node_modules
      # 掛載主機時間文件 Mount host timezone file
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=class_schedule
      - DB_USER=postgres
      - DB_PASSWORD=talent_password
      - JWT_SECRET=talent_teacher_secret_key
      - JWT_EXPIRES_IN=24h
      - TZ=Asia/Taipei
      - API_BASE_URL=http://localhost:3006
    depends_on:
      - database
    networks:
      - talent-network
    # 啟用熱重載 Enable hot reload
    command: npm run dev

  # 數據庫服務 Database service
  database:
    container_name: talent-postgres-dev
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - talent-postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      # 掛載主機時間文件 Mount host timezone file
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_DB=class_schedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=talent_password
      - TZ=Asia/Taipei
      - PGTZ=Asia/Taipei
    # 添加命令行參數來設置時區 Add command line arguments to set timezone
    command: postgres -c timezone=Asia/Taipei
    networks:
      - talent-network

# 卷定義 Volumes definition
volumes:
  talent-postgres-data:
    name: talent-postgres-data

# 網絡定義 Networks definition
networks:
  talent-network:
    name: talent-network 